###############################################################################
## dev 开发环境
###############################################################################
## 数据库设置
spring:
  datasource:
    url: jdbc:mysql://39.106.66.242:3306/xunwu?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    initialSize: 1
    minIdle: 1
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    validationQuery: SELECT 1
    filters: stat,log4j,wall,config
###############################################################################
## redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    timeout: 10000ms
    jedis:
      pool:
        max-active: 50
        max-idle: 5
        min-idle: 0
        max-wait: 10000ms
## thymeleaf
  thymeleaf:
    encoding: UTF-8
    cache: false
    mode: HTML


###############################################################################
## 日志配置路径
logging:
  config: classpath:log4j2-dev.xml
###############################################################################
## swagger配置
swagger:
  enable: true
###############################################################################

###########################################################
server:
  error:
    whitelabel:
      enabled: false
